### ISSUE TITLE
Mention @media queries in README ?

### ISSUE THREAD

**Issue by jcward** [ncannasse/hss#15]
I assume `@media` queries are supported, but it might be nice if the README used some example of them, just so it's searchable, and I can see, yes, they're supported.

Maybe something like...

```
var narrow_width = 767px;

@media only screen and (max-width : $narrow_width) {
  .hide-on-narrow { display:none !important; }
}
```

**Comment by R32** [comment]
But it just simply treats the identifier between `@media` and `{` as a string, so the variable won't work.

**Comment by R32** [comment]
I have just added support for variables and recorded it in readme, d1afc63

**Comment by jcward** [comment]
Wow, that was fast! :+1:
