### ISSUE TITLE
ie hacks, about prefix `*`

### ISSUE THREAD

**Issue by R32** [ncannasse/hss#5]
how to write this in hss???

```css
div{
  *color:#fff;
}
```

except `display:inline-blick`. sometimes, I want to customize some of these with prefix `*`

**Comment by ncannasse** [comment]
you can do
```css
div {
   CSS("*color"):#fff;
}
```
This will bypass all checks.

**Comment by R32** [comment]
But in git version or Flashdevelop 5.0, It will report an error: 

```bash
style.hss:2: Unexpected :
```
